# -*- coding: utf-8 -*-
"""KNN_Assignment13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v2C6KKfNbd6GxmQrPRF2xAtqnNwmAOxc
"""

#Social_Networks_Ads.csv

"""**Importing the libraries**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""**Importing the dataset**"""

df=pd.read_csv('/content/Social_Network_Ads.csv')
df

X=df.iloc[:,[2,3]]
X
y=df.iloc[:,-1]
y

"""**Splitting the dataset into the Training set and Test set**"""

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

"""**Feature Scaling**"""

from sklearn.preprocessing import StandardScaler
SS=StandardScaler()
X_train=SS.fit_transform(X_train)
X_test=SS.transform(X_test)

"""**Fitting K-NN to the Training set**"""

from sklearn.neighbors import KNeighborsClassifier
Knn=KNeighborsClassifier(n_neighbors=1)
Knn.fit(X_train,y_train)

print(Knn.score(X_train,y_train))

print(Knn.score(X_test,y_test))

"""**Predicting the Test set results**"""

from sklearn.metrics import accuracy_score

y_pred=Knn.predict(X_test)

"""**Making the Confusion Matrix**"""

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

